name: RemoteCommand
version: 0.1
main: io.github.bigcookie233.remotecommand.RemoteCommand
author: BigCookie233
commands:
  remotecommand:
    description: RemoteCommand
    usage: /remotecommand <command> <params>
    aliases: rm
